### ISSUE TITLE
Incorrect check multiple API versions

### ISSUE THREAD

**Issue by intech** [stoplightio/spectral-url-versioning#6]
I get the error `one-api-version-per-document Multiple API versions detected in Server URLs. servers` for the mock server from Stoplight.

```yaml
servers:
  - url: 'https://stoplight.io/mocks/my-project/docs/12345'
    description: Mock server Stoplight
  - url: 'http://localhost:3000/v1'
    description: Local
  - url: 'https://api.dev.site.com/v1'
    description: Development
  - url: 'https://api.site.com/v1'
    description: Production
```

I looked at the regular expression to check. I think it doesn't work correctly. If you specify `v1.site.com/api` and `api.site.com/v1`, it will consider them different because it selects `v1.` and `/v1` for comparison.
